version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "install phase"
      - apt update
      - apt upgrade -y
      - apt install cmake git-all g++ libpcre2-dev libssl-dev libpq-dev libpq5 -y
      - apt install default-mysql-client default-libmysqlclient-dev postgresql-client brotli libbrotli-dev -y
      - apt install unixodbc* freetds* tdsodbc libsqlite3-dev -y
      - apt install googletest -y
      - cd /usr/src/googletest
      - cmake .
      - make install
  pre_build:
    commands:
      - echo "pre-build phase"
  build:
    commands:
      - echo "build phase +"
      - cd $CODEBUILD_SRC_DIR/code
      - ls
      - cmake -DCMAKE_INSTALL_PREFIX=artifacts .
      - make -j 2
  post_build:
    commands:
      - echo "post build phase"
