# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexeyp/workspace/sptk5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexeyp/workspace/sptk5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexeyp/workspace/sptk5/CMakeFiles /home/alexeyp/workspace/sptk5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexeyp/workspace/sptk5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named tar2h

# Build rule for target.
tar2h: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tar2h
.PHONY : tar2h

# fast build rule for target.
tar2h/fast:
	$(MAKE) -f themes/CMakeFiles/tar2h.dir/build.make themes/CMakeFiles/tar2h.dir/build
.PHONY : tar2h/fast

#=============================================================================
# Target rules for targets named Blue Theme

# Build rule for target.
Blue\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "Blue Theme"
.PHONY : Blue\ Theme

# fast build rule for target.
Blue\ Theme/fast:
	$(MAKE) -f "themes/Blue/CMakeFiles/Blue Theme.dir/build.make" "themes/Blue/CMakeFiles/Blue Theme.dir/build"
.PHONY : Blue\ Theme/fast

#=============================================================================
# Target rules for targets named Dark Theme

# Build rule for target.
Dark\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "Dark Theme"
.PHONY : Dark\ Theme

# fast build rule for target.
Dark\ Theme/fast:
	$(MAKE) -f "themes/Dark/CMakeFiles/Dark Theme.dir/build.make" "themes/Dark/CMakeFiles/Dark Theme.dir/build"
.PHONY : Dark\ Theme/fast

#=============================================================================
# Target rules for targets named Default Theme

# Build rule for target.
Default\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "Default Theme"
.PHONY : Default\ Theme

# fast build rule for target.
Default\ Theme/fast:
	$(MAKE) -f "themes/Default/CMakeFiles/Default Theme.dir/build.make" "themes/Default/CMakeFiles/Default Theme.dir/build"
.PHONY : Default\ Theme/fast

#=============================================================================
# Target rules for targets named E17 Theme

# Build rule for target.
E17\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "E17 Theme"
.PHONY : E17\ Theme

# fast build rule for target.
E17\ Theme/fast:
	$(MAKE) -f "themes/E17/CMakeFiles/E17 Theme.dir/build.make" "themes/E17/CMakeFiles/E17 Theme.dir/build"
.PHONY : E17\ Theme/fast

#=============================================================================
# Target rules for targets named Flat Theme

# Build rule for target.
Flat\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "Flat Theme"
.PHONY : Flat\ Theme

# fast build rule for target.
Flat\ Theme/fast:
	$(MAKE) -f "themes/Flat/CMakeFiles/Flat Theme.dir/build.make" "themes/Flat/CMakeFiles/Flat Theme.dir/build"
.PHONY : Flat\ Theme/fast

#=============================================================================
# Target rules for targets named Keramic Theme

# Build rule for target.
Keramic\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "Keramic Theme"
.PHONY : Keramic\ Theme

# fast build rule for target.
Keramic\ Theme/fast:
	$(MAKE) -f "themes/Keramic/CMakeFiles/Keramic Theme.dir/build.make" "themes/Keramic/CMakeFiles/Keramic Theme.dir/build"
.PHONY : Keramic\ Theme/fast

#=============================================================================
# Target rules for targets named OSX Theme

# Build rule for target.
OSX\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "OSX Theme"
.PHONY : OSX\ Theme

# fast build rule for target.
OSX\ Theme/fast:
	$(MAKE) -f "themes/OSX/CMakeFiles/OSX Theme.dir/build.make" "themes/OSX/CMakeFiles/OSX Theme.dir/build"
.PHONY : OSX\ Theme/fast

#=============================================================================
# Target rules for targets named OSX_Flat Theme

# Build rule for target.
OSX_Flat\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "OSX_Flat Theme"
.PHONY : OSX_Flat\ Theme

# fast build rule for target.
OSX_Flat\ Theme/fast:
	$(MAKE) -f "themes/OSX_Flat/CMakeFiles/OSX_Flat Theme.dir/build.make" "themes/OSX_Flat/CMakeFiles/OSX_Flat Theme.dir/build"
.PHONY : OSX_Flat\ Theme/fast

#=============================================================================
# Target rules for targets named Opera Theme

# Build rule for target.
Opera\ Theme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "Opera Theme"
.PHONY : Opera\ Theme

# fast build rule for target.
Opera\ Theme/fast:
	$(MAKE) -f "themes/Opera/CMakeFiles/Opera Theme.dir/build.make" "themes/Opera/CMakeFiles/Opera Theme.dir/build"
.PHONY : Opera\ Theme/fast

#=============================================================================
# Target rules for targets named spdb5

# Build rule for target.
spdb5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spdb5
.PHONY : spdb5

# fast build rule for target.
spdb5/fast:
	$(MAKE) -f src/CMakeFiles/spdb5.dir/build.make src/CMakeFiles/spdb5.dir/build
.PHONY : spdb5/fast

#=============================================================================
# Target rules for targets named sptk5

# Build rule for target.
sptk5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sptk5
.PHONY : sptk5

# fast build rule for target.
sptk5/fast:
	$(MAKE) -f src/CMakeFiles/sptk5.dir/build.make src/CMakeFiles/sptk5.dir/build
.PHONY : sptk5/fast

#=============================================================================
# Target rules for targets named sputil5

# Build rule for target.
sputil5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sputil5
.PHONY : sputil5

# fast build rule for target.
sputil5/fast:
	$(MAKE) -f src/CMakeFiles/sputil5.dir/build.make src/CMakeFiles/sputil5.dir/build
.PHONY : sputil5/fast

#=============================================================================
# Target rules for targets named calendar_test

# Build rule for target.
calendar_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calendar_test
.PHONY : calendar_test

# fast build rule for target.
calendar_test/fast:
	$(MAKE) -f examples/CMakeFiles/calendar_test.dir/build.make examples/CMakeFiles/calendar_test.dir/build
.PHONY : calendar_test/fast

#=============================================================================
# Target rules for targets named ceditor_test

# Build rule for target.
ceditor_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ceditor_test
.PHONY : ceditor_test

# fast build rule for target.
ceditor_test/fast:
	$(MAKE) -f examples/CMakeFiles/ceditor_test.dir/build.make examples/CMakeFiles/ceditor_test.dir/build
.PHONY : ceditor_test/fast

#=============================================================================
# Target rules for targets named cgroup_test

# Build rule for target.
cgroup_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgroup_test
.PHONY : cgroup_test

# fast build rule for target.
cgroup_test/fast:
	$(MAKE) -f examples/CMakeFiles/cgroup_test.dir/build.make examples/CMakeFiles/cgroup_test.dir/build
.PHONY : cgroup_test/fast

#=============================================================================
# Target rules for targets named check_buttons

# Build rule for target.
check_buttons: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_buttons
.PHONY : check_buttons

# fast build rule for target.
check_buttons/fast:
	$(MAKE) -f examples/CMakeFiles/check_buttons.dir/build.make examples/CMakeFiles/check_buttons.dir/build
.PHONY : check_buttons/fast

#=============================================================================
# Target rules for targets named client_test

# Build rule for target.
client_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_test
.PHONY : client_test

# fast build rule for target.
client_test/fast:
	$(MAKE) -f examples/CMakeFiles/client_test.dir/build.make examples/CMakeFiles/client_test.dir/build
.PHONY : client_test/fast

#=============================================================================
# Target rules for targets named combo_test

# Build rule for target.
combo_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 combo_test
.PHONY : combo_test

# fast build rule for target.
combo_test/fast:
	$(MAKE) -f examples/CMakeFiles/combo_test.dir/build.make examples/CMakeFiles/combo_test.dir/build
.PHONY : combo_test/fast

#=============================================================================
# Target rules for targets named cscroll_test

# Build rule for target.
cscroll_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cscroll_test
.PHONY : cscroll_test

# fast build rule for target.
cscroll_test/fast:
	$(MAKE) -f examples/CMakeFiles/cscroll_test.dir/build.make examples/CMakeFiles/cscroll_test.dir/build
.PHONY : cscroll_test/fast

#=============================================================================
# Target rules for targets named datetime

# Build rule for target.
datetime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 datetime
.PHONY : datetime

# fast build rule for target.
datetime/fast:
	$(MAKE) -f examples/CMakeFiles/datetime.dir/build.make examples/CMakeFiles/datetime.dir/build
.PHONY : datetime/fast

#=============================================================================
# Target rules for targets named db_list_view

# Build rule for target.
db_list_view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_list_view
.PHONY : db_list_view

# fast build rule for target.
db_list_view/fast:
	$(MAKE) -f examples/CMakeFiles/db_list_view.dir/build.make examples/CMakeFiles/db_list_view.dir/build
.PHONY : db_list_view/fast

#=============================================================================
# Target rules for targets named dialog_test

# Build rule for target.
dialog_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dialog_test
.PHONY : dialog_test

# fast build rule for target.
dialog_test/fast:
	$(MAKE) -f examples/CMakeFiles/dialog_test.dir/build.make examples/CMakeFiles/dialog_test.dir/build
.PHONY : dialog_test/fast

#=============================================================================
# Target rules for targets named exceptions

# Build rule for target.
exceptions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exceptions
.PHONY : exceptions

# fast build rule for target.
exceptions/fast:
	$(MAKE) -f examples/CMakeFiles/exceptions.dir/build.make examples/CMakeFiles/exceptions.dir/build
.PHONY : exceptions/fast

#=============================================================================
# Target rules for targets named font_combo

# Build rule for target.
font_combo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 font_combo
.PHONY : font_combo

# fast build rule for target.
font_combo/fast:
	$(MAKE) -f examples/CMakeFiles/font_combo.dir/build.make examples/CMakeFiles/font_combo.dir/build
.PHONY : font_combo/fast

#=============================================================================
# Target rules for targets named logfile_test

# Build rule for target.
logfile_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logfile_test
.PHONY : logfile_test

# fast build rule for target.
logfile_test/fast:
	$(MAKE) -f examples/CMakeFiles/logfile_test.dir/build.make examples/CMakeFiles/logfile_test.dir/build
.PHONY : logfile_test/fast

#=============================================================================
# Target rules for targets named registry

# Build rule for target.
registry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 registry
.PHONY : registry

# fast build rule for target.
registry/fast:
	$(MAKE) -f examples/CMakeFiles/registry.dir/build.make examples/CMakeFiles/registry.dir/build
.PHONY : registry/fast

#=============================================================================
# Target rules for targets named server_test

# Build rule for target.
server_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_test
.PHONY : server_test

# fast build rule for target.
server_test/fast:
	$(MAKE) -f examples/CMakeFiles/server_test.dir/build.make examples/CMakeFiles/server_test.dir/build
.PHONY : server_test/fast

#=============================================================================
# Target rules for targets named shaped_window

# Build rule for target.
shaped_window: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shaped_window
.PHONY : shaped_window

# fast build rule for target.
shaped_window/fast:
	$(MAKE) -f examples/CMakeFiles/shaped_window.dir/build.make examples/CMakeFiles/shaped_window.dir/build
.PHONY : shaped_window/fast

#=============================================================================
# Target rules for targets named spell_checker

# Build rule for target.
spell_checker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spell_checker
.PHONY : spell_checker

# fast build rule for target.
spell_checker/fast:
	$(MAKE) -f examples/CMakeFiles/spell_checker.dir/build.make examples/CMakeFiles/spell_checker.dir/build
.PHONY : spell_checker/fast

#=============================================================================
# Target rules for targets named splitter

# Build rule for target.
splitter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 splitter
.PHONY : splitter

# fast build rule for target.
splitter/fast:
	$(MAKE) -f examples/CMakeFiles/splitter.dir/build.make examples/CMakeFiles/splitter.dir/build
.PHONY : splitter/fast

#=============================================================================
# Target rules for targets named sptk_test

# Build rule for target.
sptk_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sptk_test
.PHONY : sptk_test

# fast build rule for target.
sptk_test/fast:
	$(MAKE) -f examples/CMakeFiles/sptk_test.dir/build.make examples/CMakeFiles/sptk_test.dir/build
.PHONY : sptk_test/fast

#=============================================================================
# Target rules for targets named syslog_test

# Build rule for target.
syslog_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 syslog_test
.PHONY : syslog_test

# fast build rule for target.
syslog_test/fast:
	$(MAKE) -f examples/CMakeFiles/syslog_test.dir/build.make examples/CMakeFiles/syslog_test.dir/build
.PHONY : syslog_test/fast

#=============================================================================
# Target rules for targets named tabs_test

# Build rule for target.
tabs_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tabs_test
.PHONY : tabs_test

# fast build rule for target.
tabs_test/fast:
	$(MAKE) -f examples/CMakeFiles/tabs_test.dir/build.make examples/CMakeFiles/tabs_test.dir/build
.PHONY : tabs_test/fast

#=============================================================================
# Target rules for targets named themes_test

# Build rule for target.
themes_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 themes_test
.PHONY : themes_test

# fast build rule for target.
themes_test/fast:
	$(MAKE) -f examples/CMakeFiles/themes_test.dir/build.make examples/CMakeFiles/themes_test.dir/build
.PHONY : themes_test/fast

#=============================================================================
# Target rules for targets named thread_onexit

# Build rule for target.
thread_onexit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thread_onexit
.PHONY : thread_onexit

# fast build rule for target.
thread_onexit/fast:
	$(MAKE) -f examples/CMakeFiles/thread_onexit.dir/build.make examples/CMakeFiles/thread_onexit.dir/build
.PHONY : thread_onexit/fast

#=============================================================================
# Target rules for targets named thread_rwlock

# Build rule for target.
thread_rwlock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thread_rwlock
.PHONY : thread_rwlock

# fast build rule for target.
thread_rwlock/fast:
	$(MAKE) -f examples/CMakeFiles/thread_rwlock.dir/build.make examples/CMakeFiles/thread_rwlock.dir/build
.PHONY : thread_rwlock/fast

#=============================================================================
# Target rules for targets named thread_test

# Build rule for target.
thread_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thread_test
.PHONY : thread_test

# fast build rule for target.
thread_test/fast:
	$(MAKE) -f examples/CMakeFiles/thread_test.dir/build.make examples/CMakeFiles/thread_test.dir/build
.PHONY : thread_test/fast

#=============================================================================
# Target rules for targets named tree_test

# Build rule for target.
tree_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tree_test
.PHONY : tree_test

# fast build rule for target.
tree_test/fast:
	$(MAKE) -f examples/CMakeFiles/tree_test.dir/build.make examples/CMakeFiles/tree_test.dir/build
.PHONY : tree_test/fast

#=============================================================================
# Target rules for targets named tree_view

# Build rule for target.
tree_view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tree_view
.PHONY : tree_view

# fast build rule for target.
tree_view/fast:
	$(MAKE) -f examples/CMakeFiles/tree_view.dir/build.make examples/CMakeFiles/tree_view.dir/build
.PHONY : tree_view/fast

#=============================================================================
# Target rules for targets named unique_instance

# Build rule for target.
unique_instance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unique_instance
.PHONY : unique_instance

# fast build rule for target.
unique_instance/fast:
	$(MAKE) -f examples/CMakeFiles/unique_instance.dir/build.make examples/CMakeFiles/unique_instance.dir/build
.PHONY : unique_instance/fast

#=============================================================================
# Target rules for targets named xml_test1

# Build rule for target.
xml_test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml_test1
.PHONY : xml_test1

# fast build rule for target.
xml_test1/fast:
	$(MAKE) -f examples/xml/CMakeFiles/xml_test1.dir/build.make examples/xml/CMakeFiles/xml_test1.dir/build
.PHONY : xml_test1/fast

#=============================================================================
# Target rules for targets named xml_test2

# Build rule for target.
xml_test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml_test2
.PHONY : xml_test2

# fast build rule for target.
xml_test2/fast:
	$(MAKE) -f examples/xml/CMakeFiles/xml_test2.dir/build.make examples/xml/CMakeFiles/xml_test2.dir/build
.PHONY : xml_test2/fast

#=============================================================================
# Target rules for targets named xml_test3

# Build rule for target.
xml_test3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml_test3
.PHONY : xml_test3

# fast build rule for target.
xml_test3/fast:
	$(MAKE) -f examples/xml/CMakeFiles/xml_test3.dir/build.make examples/xml/CMakeFiles/xml_test3.dir/build
.PHONY : xml_test3/fast

#=============================================================================
# Target rules for targets named odbc_test

# Build rule for target.
odbc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odbc_test
.PHONY : odbc_test

# fast build rule for target.
odbc_test/fast:
	$(MAKE) -f examples/database/CMakeFiles/odbc_test.dir/build.make examples/database/CMakeFiles/odbc_test.dir/build
.PHONY : odbc_test/fast

#=============================================================================
# Target rules for targets named odbc_test2

# Build rule for target.
odbc_test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odbc_test2
.PHONY : odbc_test2

# fast build rule for target.
odbc_test2/fast:
	$(MAKE) -f examples/database/CMakeFiles/odbc_test2.dir/build.make examples/database/CMakeFiles/odbc_test2.dir/build
.PHONY : odbc_test2/fast

#=============================================================================
# Target rules for targets named odbc_test3

# Build rule for target.
odbc_test3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odbc_test3
.PHONY : odbc_test3

# fast build rule for target.
odbc_test3/fast:
	$(MAKE) -f examples/database/CMakeFiles/odbc_test3.dir/build.make examples/database/CMakeFiles/odbc_test3.dir/build
.PHONY : odbc_test3/fast

#=============================================================================
# Target rules for targets named postgresql_test

# Build rule for target.
postgresql_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 postgresql_test
.PHONY : postgresql_test

# fast build rule for target.
postgresql_test/fast:
	$(MAKE) -f examples/database/CMakeFiles/postgresql_test.dir/build.make examples/database/CMakeFiles/postgresql_test.dir/build
.PHONY : postgresql_test/fast

#=============================================================================
# Target rules for targets named postgresql_test2

# Build rule for target.
postgresql_test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 postgresql_test2
.PHONY : postgresql_test2

# fast build rule for target.
postgresql_test2/fast:
	$(MAKE) -f examples/database/CMakeFiles/postgresql_test2.dir/build.make examples/database/CMakeFiles/postgresql_test2.dir/build
.PHONY : postgresql_test2/fast

#=============================================================================
# Target rules for targets named sqlite3_test

# Build rule for target.
sqlite3_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqlite3_test
.PHONY : sqlite3_test

# fast build rule for target.
sqlite3_test/fast:
	$(MAKE) -f examples/database/CMakeFiles/sqlite3_test.dir/build.make examples/database/CMakeFiles/sqlite3_test.dir/build
.PHONY : sqlite3_test/fast

#=============================================================================
# Target rules for targets named directory_ds

# Build rule for target.
directory_ds: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 directory_ds
.PHONY : directory_ds

# fast build rule for target.
directory_ds/fast:
	$(MAKE) -f examples/datasources/CMakeFiles/directory_ds.dir/build.make examples/datasources/CMakeFiles/directory_ds.dir/build
.PHONY : directory_ds/fast

#=============================================================================
# Target rules for targets named imap_ds

# Build rule for target.
imap_ds: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imap_ds
.PHONY : imap_ds

# fast build rule for target.
imap_ds/fast:
	$(MAKE) -f examples/datasources/CMakeFiles/imap_ds.dir/build.make examples/datasources/CMakeFiles/imap_ds.dir/build
.PHONY : imap_ds/fast

#=============================================================================
# Target rules for targets named file_dialogs

# Build rule for target.
file_dialogs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_dialogs
.PHONY : file_dialogs

# fast build rule for target.
file_dialogs/fast:
	$(MAKE) -f examples/dialogs/CMakeFiles/file_dialogs.dir/build.make examples/dialogs/CMakeFiles/file_dialogs.dir/build
.PHONY : file_dialogs/fast

#=============================================================================
# Target rules for targets named http_connect

# Build rule for target.
http_connect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_connect
.PHONY : http_connect

# fast build rule for target.
http_connect/fast:
	$(MAKE) -f examples/net/CMakeFiles/http_connect.dir/build.make examples/net/CMakeFiles/http_connect.dir/build
.PHONY : http_connect/fast

#=============================================================================
# Target rules for targets named imap_connect

# Build rule for target.
imap_connect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imap_connect
.PHONY : imap_connect

# fast build rule for target.
imap_connect/fast:
	$(MAKE) -f examples/net/CMakeFiles/imap_connect.dir/build.make examples/net/CMakeFiles/imap_connect.dir/build
.PHONY : imap_connect/fast

#=============================================================================
# Target rules for targets named smtp_connect

# Build rule for target.
smtp_connect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smtp_connect
.PHONY : smtp_connect

# fast build rule for target.
smtp_connect/fast:
	$(MAKE) -f examples/net/CMakeFiles/smtp_connect.dir/build.make examples/net/CMakeFiles/smtp_connect.dir/build
.PHONY : smtp_connect/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... tar2h"
	@echo "... Blue Theme"
	@echo "... Dark Theme"
	@echo "... Default Theme"
	@echo "... E17 Theme"
	@echo "... Flat Theme"
	@echo "... Keramic Theme"
	@echo "... OSX Theme"
	@echo "... OSX_Flat Theme"
	@echo "... Opera Theme"
	@echo "... spdb5"
	@echo "... sptk5"
	@echo "... sputil5"
	@echo "... calendar_test"
	@echo "... ceditor_test"
	@echo "... cgroup_test"
	@echo "... check_buttons"
	@echo "... client_test"
	@echo "... combo_test"
	@echo "... cscroll_test"
	@echo "... datetime"
	@echo "... db_list_view"
	@echo "... dialog_test"
	@echo "... exceptions"
	@echo "... font_combo"
	@echo "... logfile_test"
	@echo "... registry"
	@echo "... server_test"
	@echo "... shaped_window"
	@echo "... spell_checker"
	@echo "... splitter"
	@echo "... sptk_test"
	@echo "... syslog_test"
	@echo "... tabs_test"
	@echo "... themes_test"
	@echo "... thread_onexit"
	@echo "... thread_rwlock"
	@echo "... thread_test"
	@echo "... tree_test"
	@echo "... tree_view"
	@echo "... unique_instance"
	@echo "... xml_test1"
	@echo "... xml_test2"
	@echo "... xml_test3"
	@echo "... odbc_test"
	@echo "... odbc_test2"
	@echo "... odbc_test3"
	@echo "... postgresql_test"
	@echo "... postgresql_test2"
	@echo "... sqlite3_test"
	@echo "... directory_ds"
	@echo "... imap_ds"
	@echo "... file_dialogs"
	@echo "... http_connect"
	@echo "... imap_connect"
	@echo "... smtp_connect"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

