FROM fedora:44

LABEL maintainer="Alexey Parshin alexeyp@gmail.com"

ENV TZ=Australia/Melbourne
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN yum -y update

RUN yum -y install gcc gcc-c++ cmake git
RUN yum -y install mc pcre2 pcre2-devel unixODBC unixODBC-devel postgresql-server postgresql-devel mariadb mariadb-devel sqlite sqlite-devel
RUN yum -y install fltk fltk-devel aspell aspell-devel
RUN yum -y install rpm-build ccache rsync
RUN yum -y install make libXext-devel brotli-devel
RUN yum -y install gtest-devel
RUN yum -y install mosquitto procps
RUN yum -y install nodejs-npm

COPY oracle.install/etc /etc
COPY oracle.install/usr /usr
COPY oracle.oci.install/usr /usr
RUN  ldconfig

RUN yum -y install freetds libnsl libaio
COPY freetds.conf /etc/
COPY odbc*.ini /etc/
COPY etc/xmq /etc/xmq
COPY etc/mosquitto /etc/mosquitto
RUN mkdir -p /var/log/xmq
RUN chmod 777 /var/log/xmq

RUN useradd -m alexeyp

# io_uring support for the batched socket writer; optional at build time.
RUN dnf -y install liburing-devel

VOLUME /build
