#ifndef __CACCOUNTBALANCE__
#define __CACCOUNTBALANCE__

#include <sptk5/FieldList.h>
#include <sptk5/db/QueryParameterList.h>
#include <sptk5/sptk.h>
#include <sptk5/threads/Locks.h>
#include <sptk5/wsdl/WSBasicTypes.h>
#include <sptk5/wsdl/WSComplexType.h>
#include <sptk5/wsdl/WSRestriction.h>

/**
 * WSDL complex type class CAccountBalance.
 * Generated by wsdl2cxx SPTK utility.
 */
class CAccountBalance : public sptk::WSComplexType
{
    mutable sptk::SharedMutex m_mutex; ///< Mutext that protects access to internal data

public:

   // Elements
   sptk::WSString       m_account_number;

protected:

   /**
    * Clear content and releases allocated memory (internal)
    */
   void _clear() override;

public:

   /**
    * Constructor
    * @param elementName        WSDL element name
    * @param optional bool, Is element optional flag
    */
   explicit CAccountBalance(const char* elementName="account_balance", bool optional=false) noexcept
   : sptk::WSComplexType(elementName, optional),
     m_account_number("account_number")
   {}

   /**
    * Copy constructor
    * @param other              Other element to copy from
    */
   CAccountBalance(const CAccountBalance& other) noexcept
   : sptk::WSComplexType(other),
     m_account_number(other.m_account_number)
   {
   }

   /**
    * Move constructor
    * @param other              Other element to move from
    */
   CAccountBalance(CAccountBalance&& other) noexcept
   : sptk::WSComplexType(std::move(other)),
     m_account_number(std::move(other.m_account_number))
   {
       other.clear();
   }

   /**
    * Destructor
    */
   ~CAccountBalance() override;

   /**
    * Copy assignment
    * @param other              Other element to copy from
    */
   CAccountBalance& operator = (const CAccountBalance& other)
   {
       if (&other == this)
           return *this;
       copyFrom(other);
       return *this;
   }

   /**
    * Move assignment
    * @param other              Other element to move from
    */
   CAccountBalance& operator = (CAccountBalance&& other) noexcept
   {
       if (&other == this)
           return *this;
       copyFrom(other);
       other.clear();
       return *this;
   }

   /**
    * Load CAccountBalance from XML node
    *
    * Complex WSDL type members are loaded recursively.
    * @param input              XML node containing CAccountBalance data
    */
   void load(const sptk::xml::Element* input) override;

   /**
    * Load CAccountBalance from JSON element
    *
    * Complex WSDL type members are loaded recursively.
    * @param input              JSON element containing CAccountBalance data
    */
   void load(const sptk::json::Element* input) override;

   /**
    * Load CAccountBalance from FieldList
    *
    * Only simple WSDL type members are loaded.
    * @param input              Query field list containing CAccountBalance data
    */
   void load(const sptk::FieldList& input) override;

   /**
    * Unload CAccountBalance to existing XML node
    * @param output             Existing XML node
    */
   void unload(sptk::xml::Element* output) const override;

   /**
    * Unload CAccountBalance to existing JSON node
    * @param output             Existing JSON node
    */
   void unload(sptk::json::Element* output) const override;

   /**
    * Unload CAccountBalance to Query's parameters
    * @param output             Query parameters
    */
   void unload(sptk::QueryParameterList& output) const override;
};

#endif
