#pragma once

#include <sptk5/FieldList.h>
#include <sptk5/db/QueryParameterList.h>
#include <sptk5/sptk.h>
#include <sptk5/threads/Locks.h>
#include <sptk5/wsdl/WSBasicTypes.h>
#include <sptk5/wsdl/WSComplexType.h>
#include <sptk5/wsdl/WSRestriction.h>

namespace test_service {

/**
 * WSDL complex type class CAccountBalanceResponse.
 * Generated by wsdl2cxx SPTK utility.
 */
class CAccountBalanceResponse : public sptk::WSComplexType
{
public:

   // Elements
   sptk::WSDouble                 m_account_balance {"account_balance", false};

   // Field names of simple types, that can be used to build SQL queries
   static const sptk::Strings m_fieldNames;
   static const sptk::Strings m_elementNames;
   static const sptk::Strings m_attributeNames;
   /**
    * Constructor
    * @param elementName        WSDL element name
    * @param optional           Is element optional flag
    */
   explicit CAccountBalanceResponse(const char* elementName="account_balance_response", bool optional=false) noexcept
   : sptk::WSComplexType(elementName, optional)
   {
      WSComplexType::setElements(m_elementNames, {&m_account_balance});
   }

   /**
    * Copy constructor
    * @param other              Other object
    */
   explicit CAccountBalanceResponse(const CAccountBalanceResponse& other)
   : sptk::WSComplexType(other),
     m_account_balance(other.m_account_balance)
   {
      WSComplexType::setElements(m_elementNames, {&m_account_balance});
   }

   /**
    * Move constructor
    * @param other              Other object
    */
   explicit CAccountBalanceResponse(CAccountBalanceResponse&& other) noexcept
   : sptk::WSComplexType(std::move(other)),
     m_account_balance(std::move(other.m_account_balance))
   {
      WSComplexType::setElements(m_elementNames, {&m_account_balance});
   }

   /**
    * Destructor
    */
   ~CAccountBalanceResponse() = default;

   /**
    * Copy assignment
    * @param other              Other object
    */
   CAccountBalanceResponse& operator = (const CAccountBalanceResponse& other)
   {
      m_account_balance = other.m_account_balance;
      return *this;
   }

   /**
    * Move assignment
    * @param other              Other object
    */
   CAccountBalanceResponse& operator = (CAccountBalanceResponse&& other) noexcept
   {
      m_account_balance = std::move(other.m_account_balance);
      return *this;
   }

   /**
    * Get simple field names that can be used to build SQL queries.
    * Return list of fields doesn't include fields of complex type.
    * @return list of fields as string vector
    */
   static const sptk::Strings& fieldNames() { return m_fieldNames; }

private:

   /**
    * Check restrictions
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
