#pragma once

#include <sptk5/FieldList.h>
#include <sptk5/db/QueryParameterList.h>
#include <sptk5/sptk.h>
#include <sptk5/threads/Locks.h>
#include <sptk5/wsdl/WSBasicTypes.h>
#include <sptk5/wsdl/WSComplexType.h>
#include <sptk5/wsdl/WSRestriction.h>

namespace test_service {

/**
 * WSDL complex type class CHello.
 * Generated by wsdl2cxx SPTK utility.
 */
class CHello : public sptk::WSComplexType
{
public:

   // Elements
   sptk::WSString                           m_action {"action", false};
   sptk::WSString                           m_first_name {"first_name", false};
   sptk::WSString                           m_last_name {"last_name", false};

   /**
    * Constructor
    * @param elementName        WSDL element name
    * @param optional           Is element optional flag
    */
   explicit CHello(const char* elementName="hello", bool optional=false) noexcept;

   /**
    * Copy constructor
    * @param other              Other object
    */
   CHello(const CHello& other);

   /**
    * Move constructor
    * @param other              Other object
    */
   CHello(CHello&& other) noexcept;

   /**
    * Destructor
    */
   ~CHello() = default;

   /**
    * Copy assignment
    * @param other              Other object
    */
   CHello& operator = (const CHello& other);

   /**
    * Move assignment
    * @param other              Other object
    */
   CHello& operator = (CHello&& other) noexcept;

   /**
    * Get complex type field names.
    * @param group              Field group: elements, attributes, or both
    * @return list of fields as Strings
    */
   static const sptk::Strings& fieldNames(sptk::WSFieldIndex::FieldGroup group);

private:

   /**
    * Check restrictions
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
