#pragma once

#include <sptk5/FieldList.h>
#include <sptk5/db/QueryParameterList.h>
#include <sptk5/sptk.h>
#include <sptk5/threads/Locks.h>
#include <sptk5/wsdl/WSBasicTypes.h>
#include <sptk5/wsdl/WSComplexType.h>
#include <sptk5/wsdl/WSRestriction.h>

namespace test_service {

/**
 * WSDL complex type class CHello.
 * Generated by wsdl2cxx SPTK utility.
 */
class CHello : public sptk::WSComplexType
{
public:

   // Elements
   sptk::WSString                 m_action {"action", false};
   sptk::WSString                 m_first_name {"first_name", false};
   sptk::WSString                 m_last_name {"last_name", false};

   // Field names of simple types, that can be used to build SQL queries
   static const sptk::Strings m_fieldNames;
   static const sptk::Strings m_elementNames;
   static const sptk::Strings m_attributeNames;
   /**
    * Constructor
    * @param elementName        WSDL element name
    * @param optional           Is element optional flag
    */
   explicit CHello(const char* elementName="hello", bool optional=false) noexcept
   : sptk::WSComplexType(elementName, optional)
   {
      WSComplexType::setElements(m_elementNames, {&m_action, &m_first_name, &m_last_name});
   }

   /**
    * Copy constructor
    * @param other              Other object
    */
   explicit CHello(const CHello& other)
   : sptk::WSComplexType(other),
     m_action(other.m_action),
     m_first_name(other.m_first_name),
     m_last_name(other.m_last_name)
   {
      WSComplexType::setElements(m_elementNames, {&m_action, &m_first_name, &m_last_name});
   }

   /**
    * Move constructor
    * @param other              Other object
    */
   explicit CHello(CHello&& other) noexcept
   : sptk::WSComplexType(std::move(other)),
     m_action(std::move(other.m_action)),
     m_first_name(std::move(other.m_first_name)),
     m_last_name(std::move(other.m_last_name))
   {
      WSComplexType::setElements(m_elementNames, {&m_action, &m_first_name, &m_last_name});
   }

   /**
    * Destructor
    */
   ~CHello() = default;

   /**
    * Copy assignment
    * @param other              Other object
    */
   CHello& operator = (const CHello& other)
   {
      m_action = other.m_action;
      m_first_name = other.m_first_name;
      m_last_name = other.m_last_name;
      return *this;
   }

   /**
    * Move assignment
    * @param other              Other object
    */
   CHello& operator = (CHello&& other) noexcept
   {
      m_action = std::move(other.m_action);
      m_first_name = std::move(other.m_first_name);
      m_last_name = std::move(other.m_last_name);
      return *this;
   }

   /**
    * Get simple field names that can be used to build SQL queries.
    * Return list of fields doesn't include fields of complex type.
    * @return list of fields as string vector
    */
   static const sptk::Strings& fieldNames() { return m_fieldNames; }

private:

   /**
    * Check restrictions
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
