#pragma once

#include <sptk5/FieldList.h>
#include <sptk5/db/QueryParameterList.h>
#include <sptk5/sptk.h>
#include <sptk5/threads/Locks.h>
#include <sptk5/wsdl/WSBasicTypes.h>
#include <sptk5/wsdl/WSComplexType.h>
#include <sptk5/wsdl/WSRestriction.h>

namespace test_service {

/**
 * WSDL complex type class CLoginResponse.
 * Generated by wsdl2cxx SPTK utility.
 */
class CLoginResponse : public sptk::WSComplexType
{
public:

   // Elements
   sptk::WSString                           m_jwt {"jwt", false};

   // Field names of simple types, that can be used to build SQL queries
   static const sptk::Strings              m_fieldNames;
   static const sptk::Strings              m_elementNames;
   static const sptk::Strings              m_attributeNames;
   /**
    * Constructor
    * @param elementName        WSDL element name
    * @param optional           Is element optional flag
    */
   explicit CLoginResponse(const char* elementName="login_response", bool optional=false) noexcept;

   /**
    * Copy constructor
    * @param other              Other object
    */
   CLoginResponse(const CLoginResponse& other);

   /**
    * Move constructor
    * @param other              Other object
    */
   CLoginResponse(CLoginResponse&& other) noexcept;

   /**
    * Destructor
    */
   ~CLoginResponse() = default;

   /**
    * Copy assignment
    * @param other              Other object
    */
   CLoginResponse& operator = (const CLoginResponse& other)
   {
      m_jwt = other.m_jwt;
      return *this;
   }

   /**
    * Move assignment
    * @param other              Other object
    */
   CLoginResponse& operator = (CLoginResponse&& other) noexcept
   {
      m_jwt = std::move(other.m_jwt);
      return *this;
   }

   /**
    * Get simple field names that can be used to build SQL queries.
    * Return list of fields doesn't include fields of complex type.
    * @return list of fields as string vector
    */
   static const sptk::Strings& fieldNames() { return m_fieldNames; }

private:

   /**
    * Check restrictions
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
