#pragma once

#include "CProjectInfo.h"
#include <sptk5/FieldList.h>
#include <sptk5/db/QueryParameterList.h>
#include <sptk5/sptk.h>
#include <sptk5/threads/Locks.h>
#include <sptk5/wsdl/WSBasicTypes.h>
#include <sptk5/wsdl/WSComplexType.h>
#include <sptk5/wsdl/WSRestriction.h>

namespace test_service {

/**
 * WSDL complex type class CLogin.
 * Generated by wsdl2cxx SPTK utility.
 */
class CLogin : public sptk::WSComplexType
{
public:

    /**
     * ID of the class
     */
    static sptk::String classId()
    {
        return "Login";
    }

   // Elements
   sptk::WSString                           m_username {"username", false};
   sptk::WSString                           m_password {"password", false};
   sptk::WSArray<sptk::WSString>            m_servers {"servers"};
   CProjectInfo                             m_project {"project", true};
   // Attributes
   sptk::WSInteger                          m_server_count {"server_count", true};
   sptk::WSString                           m_type {"type", true};

   /**
    * Constructor
    * @param elementName        WSDL element name
    * @param optional           Is element optional flag
    */
   explicit CLogin(const char* elementName="login", bool optional=false) noexcept;

   /**
    * Copy constructor
    * @param other              Other object
    */
   CLogin(const CLogin& other);

   /**
    * Move constructor
    * @param other              Other object
    */
   CLogin(CLogin&& other) noexcept;

   /**
    * Destructor
    */
   ~CLogin() override = default;

   /**
    * Copy assignment
    * @param other              Other object
    */
   CLogin& operator = (const CLogin& other) = default;

   /**
    * Move assignment
    * @param other              Other object
    */
   CLogin& operator = (CLogin&& other) noexcept = default;

   /**
    * Get complex type field names.
    * @param group              Field group: elements, attributes, or both
    * @return list of fields as Strings
    */
   static const sptk::Strings& fieldNames(sptk::WSFieldIndex::Group group);

private:

   /**
    * Check restrictions
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
