CREATE USER gtest
    IDENTIFIED BY test#123
    DEFAULT TABLESPACE users
    QUOTA 1000M ON users
    ;

GRANT CREATE SESSION TO gtest;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO gtest;
