<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta name="verify-v1" content="jHCfla68W2+9PfbeXofKVmlHUUklyFzeTcO8vmdlW3U=" />
<meta name="keywords" content="FLTK, SPTK, STL, CDialog, Crossplatform, PostgreSQL, Oracle, MySQL, ODBC" />
<link rel="stylesheet" type="text/css" href="standard.css" media="all" />
<title><?php echo $title ?></title>
</head>
<body>
<table cellpadding="0" cellspacing="0" class="body">
<tr><td>
<div id="top">
<table width="100%"><tr>
<td align="left"><img src="images/<?php echo $footimage ?>" alt="" /></td>
<td align="right"><img src="images/linotex_white_1.png" width="205" height="59" alt="" /></td>
<td width="20"></td>
</tr></table>

<br class="clear" />
<dl class="counter">
  <dd> <?php include("counter.inc"); ?> </dd>
</dl>
</div>