# This file is specifically for finding OpenSSL-Win64 on Windows

IF (WIN32)
   SET (OPENSSL_POSSIBLE_INCLUDE_PATHS $ENV{ProgramFiles}/OpenSSL-Win64/include)
   SET (OPENSSL_POSSIBLE_LIB_PATHS $ENV{ProgramFiles}/OpenSSL-Win64/lib/VC/x64/MD)
ENDIF (WIN32)

FIND_PATH(OPENSSL_INCLUDE_DIR ssl.h ${OPENSSL_POSSIBLE_INCLUDE_PATHS})
FIND_LIBRARY(OPENSSL_LIBRARY NAMES ssl libssl PATHS ${OPENSSL_POSSIBLE_LIB_PATHS})

IF (OPENSSL_INCLUDE_DIR AND OPENSSL_LIBRARY)
   SET(OPENSSL_FOUND TRUE)
ENDIF (OPENSSL_INCLUDE_DIR AND OPENSSL_LIBRARY)

IF (OPENSSL_FOUND)
   IF (NOT OPENSSL_FIND_QUIETLY)
      MESSAGE(STATUS "Found OpenSSL-Win64: ${OPENSSL_LIBRARY}")
   ENDIF (NOT OPENSSL_FIND_QUIETLY)
ELSE (OPENSSL_FOUND)
   IF (OPENSSL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OpenSSL-Win64")
   ENDIF (OPENSSL_FIND_REQUIRED)
ENDIF (OPENSSL_FOUND)
