# This file is specifically for finding OpenSSL-Win64 on Windows

IF (WIN32)
   SET (OPENSSL_POSSIBLE_INCLUDE_PATHS $ENV{ProgramFiles}/OpenSSL-Win64/include)
   SET (OPENSSL_POSSIBLE_LIB_PATHS $ENV{ProgramFiles}/OpenSSL-Win64/lib/VC/x64/MD)
ENDIF (WIN32)

FIND_PATH(OPENSSL_INCLUDE_DIR openssl/ssl.h ${OPENSSL_POSSIBLE_INCLUDE_PATHS})
FIND_LIBRARY(LIB_EAY_LIBRARY NAMES libcrypto PATHS ${OPENSSL_POSSIBLE_LIB_PATHS})
FIND_LIBRARY(SSL_EAY_LIBRARY NAMES libssl PATHS ${OPENSSL_POSSIBLE_LIB_PATHS})

IF (OPENSSL_INCLUDE_DIR AND LIB_EAY_LIBRARY)
   SET(OPENSSL_FOUND TRUE)

   SET(OPENSSL_SSL_LIBRARY ${SSL_EAY_LIBRARY} )
   SET(OPENSSL_CRYPTO_LIBRARY ${LIB_EAY_LIBRARY} )

   SET(OPENSSL_LIBRARIES ${LIB_EAY_LIBRARY} ${SSL_EAY_LIBRARY})

   IF (NOT OPENSSLWIN64_FIND_QUIETLY)
      MESSAGE(STATUS "Found OpenSSL-Win64: ${OPENSSL_SSL_LIBRARIES}")
   ENDIF ()
ELSE ()
   IF (OPENSSLWIN64_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OpenSSL-Win64")
   ENDIF ()
ENDIF ()
