IF (UNIX)
    EXEC_PROGRAM(uname OUTPUT_VARIABLE SYSTEM_NAME)
    SET (OS_TYPE ${SYSTEM_NAME})
    IF (${SYSTEM_NAME} STREQUAL "Linux")
        SET (LINUX TRUE)
    ELSE ()
        SET (BSD TRUE)
    ENDIF ()

    FIND_FILE(RELEASE_FILE NAMES os-release centos-release redhat-release ubuntu-release PATHS /etc)
    EXEC_PROGRAM(grep ARGS -E "^NAME=" ${RELEASE_FILE} OUTPUT_VARIABLE OS_NAME)
    STRING(REGEX MATCH "(Debian|CentOS|Ubuntu)" OS_FLAVOUR "${OS_NAME}")
ELSE ()
    SET (OS_TYPE "Windows")
ENDIF ()

IF (OS_FLAVOUR)
    MESSAGE ("OS Flavour:         ${OS_TYPE} (${OS_FLAVOUR})")
ELSE ()
    MESSAGE ("OS Type:            ${OS_TYPE}")
ENDIF ()
